# Generated by Django 3.0 on 2019-12-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passport_no', models.IntegerField()),
                ('referene', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='')),
                ('cost', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('On Hold', 'On Hold'), ('Completed', 'Completed')], max_length=255)),
            ],
        ),
    ]
